# Generated by Django 3.0.5 on 2020-06-09 04:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_title', models.CharField(max_length=128, verbose_name='公告标题')),
                ('notice_time', models.DateField(verbose_name='发布时间')),
                ('content', tinymce.models.HTMLField(max_length=10000, verbose_name='公告内容')),
            ],
            options={
                'verbose_name_plural': '公告',
            },
        ),
        migrations.CreateModel(
            name='Table_Five',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('volume_num', models.CharField(max_length=128, verbose_name='卷数')),
                ('volume', models.CharField(max_length=128, verbose_name='卷名')),
                ('title', models.CharField(max_length=128, verbose_name='表名')),
                ('mc', models.CharField(max_length=128, verbose_name='图表X列')),
                ('level_1', models.CharField(max_length=128, verbose_name='一级')),
                ('level_2', models.CharField(max_length=128, verbose_name='二级')),
                ('total', models.CharField(max_length=128, verbose_name='数值')),
            ],
            options={
                'verbose_name_plural': '第五次人口普查',
            },
        ),
        migrations.CreateModel(
            name='Table_Six',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('volume_num', models.CharField(max_length=128, verbose_name='卷数')),
                ('volume', models.CharField(max_length=128, verbose_name='卷名')),
                ('title', models.CharField(max_length=128, verbose_name='表名')),
                ('mc', models.CharField(max_length=128, verbose_name='图表X列')),
                ('level_1', models.CharField(max_length=128, verbose_name='一级')),
                ('level_2', models.CharField(max_length=128, verbose_name='二级')),
                ('total', models.CharField(max_length=128, verbose_name='数值')),
            ],
            options={
                'verbose_name_plural': '第六次人口普查',
            },
        ),
    ]
